/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1.1/userguide/multi_project_builds.html
 */

dependencyResolutionManagement {

    versionCatalogs {
        create("libs") {
            version("arrow", "2.0.1")
            version("kotlin-logging", "7.0.3")
            version("hoplite", "2.8.2")
            version("logback", "1.5.19")
            version("logstash", "7.4")
            version("json-schema-core", "0.0.2")
            version("kotlinx-serialization", "1.9.0")
            version("jaxb-api", "2.4.0-b180830.0359")
            version("migesok-time-adapters", "1.1.3")

            library("arrow-core", "io.arrow-kt", "arrow-core").versionRef("arrow")
            library("arrow-functions", "io.arrow-kt", "arrow-functions").versionRef("arrow")

            library("hoplite-core", "com.sksamuel.hoplite", "hoplite-core").versionRef("hoplite")
            library("hoplite-hocon", "com.sksamuel.hoplite", "hoplite-hocon").versionRef("hoplite")

            library("kotlin-logging", "io.github.oshai", "kotlin-logging-jvm").versionRef("kotlin-logging")
            library("logback-classic", "ch.qos.logback", "logback-classic").versionRef("logback")
            library("logback-logstash", "net.logstash.logback", "logstash-logback-encoder").versionRef("logstash")

            library(
                "kotlinx-serialization-json",
                "org.jetbrains.kotlinx",
                "kotlinx-serialization-json"
            ).versionRef("kotlinx-serialization")

            library("json-schema-core", "no.nav.helsemelding", "json-schema-core").versionRef("json-schema-core")

            library("javax-jaxb-api", "javax.xml.bind", "jaxb-api").versionRef("jaxb-api")

            library("migesok-jaxb-time-adapters", "com.migesok", "jaxb-java-time-adapters").versionRef("migesok-time-adapters")

            library("nav-xml-hodemelding", "no.nav.helse.xml", "kith-hodemelding").version("2019.07.30-12-26-5c924ef4f04022bbb850aaf299eb8e4464c1ca6a")
            library("nav-xml-dialogmelding", "no.nav.helse.xml", "dialogmelding").version("1.5d21db9")
            library("nav-xml-base64Container", "no.nav.helse.xml", "base64Container").version("1.5ac2176")
            library("nav-xml-apprec", "no.nav.helse.xml", "kith-apprec").version("2019.07.30-04-23-2a0d1388209441ec05d2e92a821eed4f796a3ae2")

            bundle("logging", listOf("logback-classic", "logback-logstash"))
            bundle("nav-xml", listOf("nav-xml-hodemelding", "nav-xml-dialogmelding", "nav-xml-base64Container", "nav-xml-apprec"))
        }

        create("testLibs") {
            version("arrow", "2.0.0")
            version("ktor", "3.3.1")
            version("ktor-server-test", "3.3.1")
            version("kotest", "5.9.1")
            version("testcontainers", "1.18.1")
            version("kotest-extensions", "2.0.2")

            library("ktor-server-test-host", "io.ktor", "ktor-server-test-host").versionRef("ktor-server-test")
            library("ktor-client-mock", "io.ktor", "ktor-client-mock").versionRef("ktor")

            library("kotest-runner-junit5", "io.kotest", "kotest-runner-junit5").versionRef("kotest")
            library("kotest-framework-datatest", "io.kotest", "kotest-framework-datatest").versionRef("kotest")
            library("kotest-extensions-jvm", "io.kotest", "kotest-extensions-jvm").versionRef("kotest")

            library(
                "kotest-extensions-testcontainers",
                "io.kotest.extensions",
                "kotest-extensions-testcontainers"
            ).versionRef("kotest-extensions")

            library("kotest-assertions-arrow", "io.kotest.extensions", "kotest-assertions-arrow").versionRef("arrow")

            library("testcontainers", "org.testcontainers", "testcontainers").versionRef("testcontainers")
            library("testcontainers-postgresql", "org.testcontainers", "postgresql").versionRef("testcontainers")

            bundle("kotest", listOf("kotest-runner-junit5", "kotest-framework-datatest"))
        }
    }

    repositories {
        mavenCentral()
        maven {
            name = "Nav token-support"
            url = uri("https://maven.pkg.github.com/navikt/token-support")
            credentials {
                username = "token"
                password = System.getenv("GITHUB_TOKEN")
            }
        }
        maven {
            name = "Mock OAUTH2 server"
            url = uri("https://maven.pkg.github.com/navikt/mock-oauth2-server")
            credentials {
                username = "token"
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

rootProject.name = "helsemelding-message-converter"
